### ISSUE TITLE
安装penMods后无法输入大写字母

### ISSUE THREAD

**Issue by Alicedrop** [PenUniverse/PenMods-release#100]
### 异常模块

PenMods (由Mod修改导致的)

### 词典笔型号

YDP02x

### PenMods 版本

1.1.8

### 词典笔系统版本

2.0.7

### 发生了什么?

penMods输入法是没有大写字母的，这对输wifi密码等场景有严重影响，同时查单词也只能通过扫描输入缩写。回车键可以放在符号里，空格旁边

### 复现此问题的步骤

在wifi连接界面任意连接一个带密码的wifi即可打开键盘，安装penmods后的键盘没有了ABC选项，被一个回车键取代。回车键可以放在符号里，空格旁边

**Comment by Redbeanw44602** [comment]
你点下小写abc按钮试试
