### ISSUE TITLE
一个无法正常使用New bing的问题

### ISSUE THREAD

**Issue by FHR2048** [PenUniverse/PenMods-release#107]
### 异常模块

PenMods (由Mod修改导致的)

### 词典笔型号

YDP02x

### PenMods 版本

1.2.0

### 词典笔系统版本

2.0.7

### 发生了什么?

在清除所有cookie后,我访问bing.com/chat,把cookies导出到json粘贴到bing-cookies.json,覆盖到Music/,然后访问cn.bing.com/turing/conversation/create成功申请了一个converdation,最后在词典笔上显示：

       json异常:
      <html><head><title>Obejct moved</tltle></head><body>
      <h2>Obejct moved to <a href="https://cn.bing.com/turing/conversation/create">here</a>.</h2>
      </body></html>][json.exception.parse_error.101] parse error at line 1,column 1:syntax error while parsing value -invalid literal; last read: '<'

**Comment by FHR2048** [comment]
json异常:
[<html><head><title>Obejct moved</tltle></head><body>
<h2>Obejct moved to <a href="https://cn.bing.com/turing/conversation/create">here</a>.</h2>
</body></html>
][json.exception.parse_error.101] parse error at line 1,column 1:syntax error while parsing value -invalid literal; last read: '<'

**Comment by Redbeanw44602** [comment]
使用代理，具体见群公告信息
