### ISSUE TITLE
bing chatbox报错代码10

### ISSUE THREAD

**Issue by BlackWinds05** [PenUniverse/PenMods-release#108]
### 异常模块

PenMods (由Mod修改导致的)

### 词典笔型号

YDP02x

### PenMods 版本

1.2.0

### 词典笔系统版本

2.0.7

### 发生了什么?

按正确步骤进行操作并覆盖cookies后
提问问题 返回错误信息：
套接字发生错误，代码：10。

### 复现此问题的步骤

更新版本1,20
替换cookies
替换signature和Bing ChatHub为群内公告版本
进行提问
发生错误，返回错误信息

**Comment by DSFdsfWxp** [comment]
chathub 链接的协议应该是 wss 而不是 https ，更正设置后可正常使用。
