### ISSUE TITLE
修改文件名相关UI bug

### ISSUE THREAD

**Issue by Alicedrop** [PenUniverse/PenMods-release#109]
### 异常模块

PenMods (由Mod修改导致的)

### 词典笔型号

YDP02x

### PenMods 版本

1.1.8

### 词典笔系统版本

2.0.7

### 发生了什么?

在一个文件夹内点击修改文件名，再点左上角返回到上一级目录仍处在修改文件名状态，但不显示修改文件名状态的那个笔标志

### 复现此问题的步骤

1.在一个文件夹内点击修改文件名，再点左上角返回到上一级目录
2.此时文件后面没有修改文件名的标志，点击任意文件仍会弹出修改文件名页面

**Comment by Redbeanw44602** [comment]
更新1.2.0
