### ISSUE TITLE
重置选项增加利用a/b分区功能

### ISSUE THREAD

**Issue by JetSquid** [PenUniverse/PenMods-release#11]
使用penmods1.1.0时偶然发现如果a分区寄了，系统会启动到b分区，并把b分区覆盖到a分区，我b分区装了penmods，覆盖后a分区也有penmods，系统有还原操作，ab分区是互相保护的，如果有时间，希望可以利用一下这个功能，
例如：
1.提前把安装了penmods的a分区覆盖到b分区，假如使用的a分区出问题，系统会自动启动到b
分区并把b分区覆盖到a分区实现不掉penmods的功能。
2.b分区是原版系统，a分区是安装了penmods的系统，使用者在用a分区时因为某种原因想要删除penmods，可以直接利用分区机制将原版本系统覆盖还原，在下次安装时可以不用重刷system分区即可重装penmods。
........

**Comment by Redbeanw44602** [comment]
A/B 分区是无缝更新所使用的，不打算增加更多用途。

另外，1.1.0的 PenMods 卸载后不需要重刷分区即可重装。
