### ISSUE TITLE
语音助手增强

### ISSUE THREAD

**Issue by Alicedrop** [PenUniverse/PenMods-release#110]
### 您遇到了什么问题？

语音助手由于语音识别率不稳定，经常难以搜索需要的内容，而且常常搜索不到结果显示“有道还在学习中，问点别的吧”，实际上百度一搜一大堆。

### 您认为还缺少什么？

1.可以通过扫描、打字、语音输入来输入语音助手搜索内容
2.可以自己设置语音识别API、搜索API，并且可以添加并同时使用多个源：这样可以搜索各个领域、方向的内容（举个例子，同时用百度\bing），方便找到需要的结果。具体类似于国内手机厂商的“智慧搜素”之类的搜素结果包括在应用商店、本机应用列表、搜索引擎、地图等方面的内容

**Comment by Redbeanw44602** [comment]
参见1.2.0的New Bing支持，语音助手是有道控制的，你在这里提建议完全没有意义。
