### ISSUE TITLE
设备重启后自动发音被自动打开

### ISSUE THREAD

**Issue by JunJimJun** [PenUniverse/PenMods-release#114]
### 异常模块

PenMods (由Mod修改导致的)

### 词典笔型号

YDP02x

### PenMods 版本

1.2.0

### 词典笔系统版本

2.0.7

### 发生了什么?

每次重启设备后自动发音都会被重设到开启状态。
确认卸载PenMods后没有这个问题。

### 复现此问题的步骤

1.在设置中关闭自动发音
2.硬重启
3.自动发音又被开启

**Comment by Chen017** [comment]
的确是这样

**Comment by Redbeanw44602** [comment]
暂时先在安全选项里关掉自动发音，下个版本会修复这个问题。
