### ISSUE TITLE
8G版本无法安装

### ISSUE THREAD

**Issue by Stannum138** [PenUniverse/PenMods-release#120]
### 异常模块

PenMods (由Mod修改导致的)

### 词典笔型号

YDP02x

### PenMods 版本

1.1.0

### 词典笔系统版本

2.0.7

### 发生了什么?

已经安装满分版系统，按照安装软件说明安装，软件显示安装成功，但是笔上并没有安装，多次尝试后依旧无法安装，笔为ydp021的8G版本

按照b站的方法刷机以后，笔上显示储存容量为16gb，不知道和这个有没有关系

**Comment by Redbeanw44602** [comment]
8G版本没有userdisk分区，我手头也没有8G的样本，所以没法适配。

**Comment by Charlie-tina** [comment]
之前群里面有8G适配的满分版固件，各位还有那个网盘链接吗？

**Comment by rl9051** [comment]
我是二代8g版本，我测试了群里最新的2.1.2满分版固件。刷机后，词典笔上显示16gb容量。但是我可以格式化第14分区，得到userdisk分区。我没有安装penmods，目前看来一切正常。我疑惑的是，按照教程提示8GB版本没有userdisk，但是我可以格式化得到userdisk。

**Comment by Redbeanw44602** [comment]
> 我是二代8g版本，我测试了群里最新的2.1.2满分版固件。刷机后，词典笔上显示16gb容量。但是我可以格式化第14分区，得到userdisk分区。我没有安装penmods，目前看来一切正常。我疑惑的是，按照教程提示8GB版本没有userdisk，但是我可以格式化得到userdisk。

你可能搞错了你的版本（观察发现有些出货是16G的闪存，但是没有开放相关存储功能）
