### ISSUE TITLE
修复没有配置歌词的mp3在播放时失去标题的情况

### ISSUE THREAD

**Issue by wmx114** [PenUniverse/PenMods-release#127]
### 您遇到了什么问题？

有时候重启词典笔然后播放音乐，先播放有歌词的mp3，再播放没有歌词的mp3，这时候没有歌词的mp3就会连标题都显示不出来，或者卡bug
![16830858316772804001856049085260](https://user-images.githubusercontent.com/132419198/235829574-135ee920-7d8b-44f5-8207-6c9f92302575.jpg)

### 您认为还缺少什么？

能否发现并修复一下上面的问题

**Comment by wmx114** [comment]
是不是和#68一样的bug？

**Comment by Redbeanw44602** [comment]
#56

**Comment by Redbeanw44602** [comment]
1.3.0已重新实现相关逻辑，如有问题请reopen issue
