### ISSUE TITLE
录音功能的三角形按键失效

### ISSUE THREAD

**Issue by wmx114** [PenUniverse/PenMods-release#129]
### 您遇到了什么问题？

尝试了多种点击方式，发现三角形的播放键没有效果。录完音之后点击✓，录音就被保存了，也无法按三角形播放

### 您认为还缺少什么？

应该是在录音的时候三角形剪头变成暂停键，录音完成之后可以点击三角形按键播放刚刚录的音频

**Comment by Redbeanw44602** [comment]
duplicate #70
