### ISSUE TITLE
录音机无法完整录音，有明显中断现象

### ISSUE THREAD

**Issue by luluandpipi** [PenUniverse/PenMods-release#13]
**录音机无法完整录音，有明显中断现象。
计时不会停止，但有时候录到一半实际上就中断了，后来的声音就不会被录制了。**

**Comment by Redbeanw44602** [comment]
请提供复现方法

**Comment by luluandpipi** [comment]
> 请提供复现方法

复现方法：

- 录个大约2分钟的音频（最好有清晰可分辨的声音）
- 看看录出来是不是少了许多
