### ISSUE TITLE
随机播放设置

### ISSUE THREAD

**Issue by wmx114** [PenUniverse/PenMods-release#134]
### 您遇到了什么问题？

个人认为随机播放还是还原成原装的：调成随机播放模式之后，点击下一首歌就是随机的而不是歌单按顺序的下一首。因为有时候想随机从歌单听一首歌，就没有办法直接随机，要把一首歌拉到尾才能随机到下一首。

### 您认为还缺少什么？

建议恢复原本随机播放的方式或者在设置中加一个选择。

**Comment by Redbeanw44602** [comment]
#56
