### ISSUE TITLE
播放歌单中断

### ISSUE THREAD

**Issue by wmx114** [PenUniverse/PenMods-release#135]
### 异常模块

PenMods (由Mod修改导致的)

### 词典笔型号

YDP02x

### PenMods 版本

1.2.0

### 词典笔系统版本

2.0.7

### 发生了什么?

播放文件夹A里的音乐时，如果我打开B文件夹，就会导致下一首歌自动播放B文件夹里的歌，这就导致如果我打开一个我装着txt文档的文件夹看小说时，音乐就无法跳转到下一首，因为这个文件夹里没有音乐。

### 复现此问题的步骤

打开A文件夹，点击一首歌
跳转到一个没有音乐的文件夹，这时候通过小弹窗点进音乐播放界面，点击下一首，就无法跳转到下一首歌

**Comment by Redbeanw44602** [comment]
Duplicate of #30.
