### ISSUE TITLE
错误地自动切歌

### ISSUE THREAD

**Issue by wmx114** [PenUniverse/PenMods-release#136]
### 异常模块

YoudaoDictPen（词典笔主程序自身）

### 词典笔型号

YDP02x

### PenMods 版本

1.2.0

### 词典笔系统版本

2.0.7

### 发生了什么?

播放音乐时，跳转到单词本界面（其他界面也类似），当我点开一个单词的详细解释，点击左上角退出，这时候我播放到一半的音乐就会被切掉，自动播放下一首

### 复现此问题的步骤

如上

**Comment by Redbeanw44602** [comment]
自动播放下一首？我这里测试的结果是音乐会暂停，但浮球没有消失😕

**Comment by Redbeanw44602** [comment]
#56

**Comment by wmx114** [comment]
会暂停而且清除播放进度

**Comment by wmx114** [comment]
会暂停播放并且清除播放进度。好像是原版词典笔会换下一首。。。

**Comment by Redbeanw44602** [comment]
原版笔也是暂停播放+清除播放进度啊。
