### ISSUE TITLE
安装第三方应用

### ISSUE THREAD

**Issue by zez20100207** [PenUniverse/PenMods-release#138]
### 避免发送重复的功能请求

- [X] 我已查看所有打开的 Issues，确保这个功能没有被提出过

### 您遇到了什么问题？

我发现即使打开了adb，安装应用后会显示缺少pm命令，且无法打开。

### 您认为还缺少什么？

能否增加一个我的应用版面，以支持第三方应用

**Comment by Redbeanw44602** [comment]
这不是Android系统，无法使用pm。

有关外部App（Linux）的支持请看 #71
