### ISSUE TITLE
在随机播放的情况下，若随机到一首在文件夹内未加载出来的歌曲，则播放会停止

### ISSUE THREAD

**Issue by sctop** [PenUniverse/PenMods-release#144]
### 避免发送重复的问题报告

- [X] 我已检查所有打开的 Issues，确保这个问题没有被提出过

### 异常模块

YoudaoDictPen（词典笔主程序自身）

### 词典笔型号

YDP02x

### PenMods 版本

1.2.0

### 词典笔系统版本

2.0.7

### 发生了什么?

这个问题可能从标题上看比较抽象，但其行为基本上如下：

1. 假设你的文件夹里有80首歌曲，而受有道一次性加载的限制，你只加载了前10或20首歌。
2. 在这已经加载的歌曲中，选择一首歌进行播放，然后将播放模式调整为“随机播放”
3. 当随机到已经加载出来的歌曲时，随机播放正常
4. 然而，当随机到这20首以外的歌曲时（例如第50首歌），则播放会停止

这个问题实际上一开始我也不清楚是什么原因，但是当某次我无聊把整个列表都加载完全之后，突然间就发现整个晚修期间听的音乐都没中断过了……后来我故意不加载完全，然后完美复现这个问题。

值得注意的是，如果是手动单击“上一曲”或“下一曲”按钮的话，则仍可以正常随机。该问题只会发生在 **自动随机到下一首曲子** 且 **该曲子尚未在文件夹中显示** 的时候。

**如果PenMods正常加载的话，可以通过调大“列式数据库”的单次查询数量限制来尽量规避这个问题。**（我就是掉Mod之后，恢复到原来的最大单次10个才发现的……）

### 复现此问题的步骤

1. 找到一个存储了较多歌曲的文件夹（建议至少30首以上）
2. 进入文件夹后，随机选取一首歌进行播放，并切换至 随机播放 模式
3. 等待播放出现异常暂停（因为有概率会随机到已经加载出的曲子，**所以曲库越大越容易发现这个问题**）

欲完全规避这个问题（逆向发现这个bug）：

1. 一直滑文件夹，直到所有曲子都加载完毕
2. 选择一首曲子，开始随机播放。

PenMods用户请注意，如欲自己尝试复现此Bug，请将 “列式数据库”的单次查询数量限制 调低，否则不好搞。

**Comment by Redbeanw44602** [comment]
emm按理说应该没有出这个问题的道理，因为PenMods的随机播放逻辑和加载了多少乐曲完全没关系。。。

**Comment by sctop** [comment]
> emm按理说应该没有出这个问题的道理，因为PenMods的随机播放逻辑和加载了多少乐曲完全没关系。。。

抱歉回复晚了，在学校困了13天……

经过测试后，即便是在PenMods正常加载的情况下，目录加载不全还是会导致这个问题。

我倾向于认为可能是音乐播放器本身的问题，可能作者大大需要在之后版本里更新的播放器中规避一下。

**Comment by Redbeanw44602** [comment]
1.3.0 已重新实现与文件管理器相关的全部逻辑，若还有问题请reopen issue。
