### ISSUE TITLE
增加关于超级词典的系统破解

### ISSUE THREAD

**Issue by I-good-vegetable-a** [PenUniverse/PenMods-release#146]
### 避免发送重复的功能请求

- [X] 我已查看所有打开的 Issues，确保这个功能没有被提出过

### 您遇到了什么问题？

我发现在所有网易的词典设备中，只有超级词典暂时在此论坛中未提及。希望能增加关于超级词典的内容

### 您认为还缺少什么？

希望得到超级词典的boot.img文件

**Comment by Redbeanw44602** [comment]
没有相关计划。
