### ISSUE TITLE
开机有概率卡有道屏后自动重启

### ISSUE THREAD

**Issue by Chengzi600** [PenUniverse/PenMods-release#147]
### 避免发送重复的问题报告

- [X] 我已检查所有打开的 Issues，确保这个问题没有被提出过

### 异常模块

PenMods (由Mod修改导致的)

### 词典笔型号

YDPG-3

### PenMods 版本

1.1.8

### 词典笔系统版本

1.0.3

### 发生了什么?

开机时，有概率出现卡有道屏情况，约30秒后重启才能进入系统
且有时重启一遍还会重复卡屏，再次重启方能进入
卡屏期间屏幕亮度被调节，且点按笔头会开启笔头灯

### 复现此问题的步骤

较易复现，出现概率达40%，二次重启概率较小

**Comment by Redbeanw44602** [comment]
#16 

原因相同
