### ISSUE TITLE
请求通过官方开源部分适配2.7.3

### ISSUE THREAD

**Issue by AronnaxM** [PenUniverse/PenMods-release#149]
### 避免发送重复的功能请求

- [X] 我已查看所有打开的 Issues，确保这个功能没有被提出过

### 您认为还缺少什么？

本人使用的YDP038近日升级至2.7.3后发现有道开放了修改源代码的功能，可以直接接上电脑在MTP中找到Qtlib文件夹并传入自定义库进行修改，也许这种方法可以简化Penmod的安装过程并提高效率，并开发更多第三方库，希望作者能够早日适配，并祝愿Penmod项目越来越好❤

**Comment by Redbeanw44602** [comment]
那个功能对PenMods适配完全没有用。
