### ISSUE TITLE
无法输入大写字母导致无法联网

### ISSUE THREAD

**Issue by x405x** [PenUniverse/PenMods-release#152]
### 避免发送重复的问题报告

- [X] 我已检查所有打开的 Issues，确保这个问题没有被提出过

### 异常模块

PenMods (由Mod修改导致的)

### 词典笔型号

YDP02x

### PenMods 版本

1.2.0

### 词典笔系统版本

2.1.2

### 发生了什么?

安装 **PenMods** 后，无法输入大写字母，在连接密码中含有大写字母的 Wi-Fi 时，没办法输入正确的密码

### 复现此问题的步骤

- 尝试连接 Wi-Fi  
- Wi-Fi 密码中有大写字母  
- 无法输入正确的密码

**Comment by xdfx2017** [comment]
……

**Comment by xdfx2017** [comment]
……
长按小写字母就可以输入大写字母

**Comment by Redbeanw44602** [comment]
点两次小写字母键就可以切换为大写...
另外PenMods暂时未修改联网相关，若无法联网请问有道客服。
