### ISSUE TITLE
YDP031型词典笔开源且允许修改

### ISSUE THREAD

**Issue by FFDVDGD** [PenUniverse/PenMods-release#153]
### 避免发送重复的功能请求

- [X] 我已查看所有打开的 Issues，确保这个功能没有被提出过

### 您遇到了什么问题？

今天发现词典笔3（我是首发买的3，不带x之类的后缀，应该官方不会更词典笔OS了，系统停留在2.7.3）在关于里新增了“开源软件使用许可”，点进去可以允许修改软件
![CRnall_20231004_215355080](https://github.com/PenUniverse/PenMods-release/assets/82321430/bfeca881-5b6e-4c12-b620-62df6b8abfb0)
。连接电脑可以查看到如下文件
![Screenshot_2023-10-04-21-54-23-690_com limelight-edit](https://github.com/PenUniverse/PenMods-release/assets/82321430/28c72ec7-b759-4d3c-8b8b-282c9a7c21df)

### 您认为还缺少什么？

请问能否增添适配？应该比较好做吧（。
![CRnall_20231004_213739440](https://github.com/PenUniverse/PenMods-release/assets/82321430/32109483-55c9-42a3-9090-402617bf6d99)
![CRnall_20231004_213730290](https://github.com/PenUniverse/PenMods-release/assets/82321430/fe8204c8-b89d-4f3e-90c1-b0c3868f4fcb)
![CRnall_20231004_213717507](https://github.com/PenUniverse/PenMods-release/assets/82321430/5a5dc7ed-d378-44ec-ba01-bb949f56b2ab)
此外是一些词典笔显示的信息

**Comment by Orange-Black** [comment]
2.7.3系统的adb密码还是CherryYoudao吗？

**Comment by FFDVDGD** [comment]
> 2.7.3系统的adb密码还是CherryYoudao吗？

是的，我连过，用搞机工具箱还能读出开机时间

**Comment by Orange-Black** [comment]
> > 2.7.3系统的adb密码还是CherryYoudao吗？
> 
> 是的，我连过，用搞机工具箱还能读出开机时间 ![image](https://user-images.githubusercontent.com/82321430/273454658-d584c950-6320-40fe-b922-fd29bb4ff0d1.png)

确定是2.7.3的密码吗？我听说2.7.3改了密码，如果还是CherryYoudao，那我就放心升了。

**Comment by FFDVDGD** [comment]
> > > 2.7.3系统的adb密码还是CherryYoudao吗？
> > 
> > 是的，我连过，用搞机工具箱还能读出开机时间 ![image](https://user-images.githubusercontent.com/82321430/273454658-d584c950-6320-40fe-b922-fd29bb4ff0d1.png)
> 
> 确定是2.7.3的密码吗？我听说2.7.3改了密码，如果还是CherryYoudao，那我就放心升了。

确定，我的笔可以连上

**Comment by Orange-Black** [comment]
> > > > 2.7.3系统的adb密码还是CherryYoudao吗？
> > > 
> > > 
> > > 是的，我连过，用搞机工具箱还能读出开机时间 ![image](https://user-images.githubusercontent.com/82321430/273454658-d584c950-6320-40fe-b922-fd29bb4ff0d1.png)
> > 
> > 
> > 确定是2.7.3的密码吗？我听说2.7.3改了密码，如果还是CherryYoudao，那我就放心升了。
> 
> 确定，我的笔可以连上

好的，谢谢，我升了🙂

**Comment by Redbeanw44602** [comment]
只是允许修改“开源软件部分”这里的开源软件特指Qt。
不建议现在打开这个东西，我最近会写篇文章说这个。
