### ISSUE TITLE
文档定位最近一次查看位置

### ISSUE THREAD

**Issue by wuozhi** [PenUniverse/PenMods-release#154]
### 避免发送重复的功能请求

- [X] 我已查看所有打开的 Issues，确保这个功能没有被提出过

### 您遇到了什么问题？

打开文档，如电子书之类的TXT，md文件时每次都需要从头开始翻

### 您认为还缺少什么？

可否添加一个定位上次查看位置的功能

**Comment by Redbeanw44602** [comment]
#63
