### ISSUE TITLE
请求支持查看png/jpg等图片格式

### ISSUE THREAD

**Issue by ghost** [PenUniverse/PenMods-release#158]
### 避免发送重复的功能请求

- [X] 我已查看所有打开的 Issues，确保这个功能没有被提出过

### 您认为还缺少什么？

支持查看图片

**Comment by FHR2048** [comment]
md语法可以实现，麻烦点
https://dictpen.amd.rocks/topic/78/%E5%9C%A8%E8%AF%8D%E5%85%B8%E7%AC%94%E4%B8%AD%E6%9F%A5%E7%9C%8B%E7%BD%91%E7%BB%9C%E5%9B%BE%E7%89%87/9
