### ISSUE TITLE
软重启有时无法再拉起主程序

### ISSUE THREAD

**Issue by luluandpipi** [PenUniverse/PenMods-release#16]
**终止主程序后，有几率无法再次启动**
测试了一下，没安装 Mods 时终止主程序后100%可以自动重启，但安装 Mods 后有时无法自动重启，会保持黑屏状态

**Comment by Redbeanw44602** [comment]
暂时没确定不能重新启动的原因到底是什么，感觉有四个点：
1. 主程序还未开始加载时就注入了（但是多次重启却无法复现问题）
2. 配置文件加载时机错误，抛出异常未捕获
3. Mod的全局变量初始化失败，抛出异常未捕获
4. 动态寻找符号失败，导致卡住（因为寻找不存在的符号耗时极长，需要遍历每个模块）

对2、3我做了些改善，在确认问题解决前不会关闭此Issue。

**Comment by JetSquid** [comment]
1.多次kidp也就是killall -9 YoudaoDictPen后出现重启ab分区覆盖
2.持续进行penmods的ota后会无法拉起主程序
3.通过penmods的ota更新完，有概率切换分区
