### ISSUE TITLE
直接恢复出厂，无法重新安装PenMods

### ISSUE THREAD

**Issue by FHR2048** [PenUniverse/PenMods-release#161]
### 避免发送重复的问题报告

- [X] 我已检查所有打开的 Issues，确保这个问题没有被提出过

### 异常模块

PenMods (由Mod修改导致的)

### 词典笔型号

YDP02x

### PenMods 版本

1.2.0

### 词典笔系统版本

2.1.2

### 发生了什么?

遇到bug,未卸载Penmods,选择直接恢复出厂，但恢复出厂后Penmods并没有成功卸载，也没有功能界面，无法重新安装，该怎么办？

### 复现此问题的步骤

“Assertion Failed: 当前系统已安装PenMods，请先还原系统再执行安装。”
并没有卸载Penmods选项，毕竟恢复出厂了

**Comment by FHR2048** [comment]
再次恢复出厂也没有用，重新刷机可以解决，所以为什么恢复出厂卸载不了呢

**Comment by Redbeanw44602** [comment]
1.3.0中PenMods注入方式和安装流程都有重大修改，理论上已规避此问题，请留意Installer更新。
