### ISSUE TITLE
优化AI种类和使用体验

### ISSUE THREAD

**Issue by Aftnos** [PenUniverse/PenMods-release#166]
### 避免发送重复的功能请求

- [X] 我已查看所有打开的 Issues，确保这个功能没有被提出过

### 您遇到了什么问题？

在使用词典笔的时候
1.词典笔多行扫描时会出现重复弹出词汇，多行扫描会卡死
2.录音很容易造成假死，而且开始录音和结束录音按钮太小了。。。。。

### 您认为还缺少什么？

1.添加opneai的官方api调用和中转api调用（chatGPT3.5-4.0）
2.增加相机功能
3.优化设计逻辑，某些关键性按钮太小了
4.支持openai的tts语言和语言输入

**Comment by Redbeanw44602** [comment]
要不你去看看别人是怎么提issue的？
