### ISSUE TITLE
防词典笔扫描功能误触

### ISSUE THREAD

**Issue by nosgk** [PenUniverse/PenMods-release#167]
### 避免发送重复的功能请求

- [X] 我已查看所有打开的 Issues，确保这个功能没有被提出过

### 您遇到了什么问题？

老是不小心激活到末端的扫描器，强制关闭音乐 强制上层显示

### 您认为还缺少什么？

添加一个防止词典笔强制进行扫描的可选开关，功能大概是在按到词典笔末端按钮时(不亮灯)不扫描 什么也不发生

**Comment by Redbeanw44602** [comment]
#159
