### ISSUE TITLE
增加国内大模型支持

### ISSUE THREAD

**Issue by Zack-2023** [PenUniverse/PenMods-release#196]
### 避免发送重复的功能请求

- [X] 我已查看所有打开的 Issues，确保这个功能没有被提出过

### 您遇到了什么问题？

Bing Chat需要代理带来很多不便

### 您认为还缺少什么？

增加国内大模型的支持 如erine 这在New Bing接口已经实现的基础上应该可以做到

**Comment by Zack-2023** [comment]
探路
我这里erine的网页端需要阻止请求https://dlswbr.baidu.com/heicha/mm/2118/acs-2118.js?_=237422和
https://miaowu.baidu.com/sdk/heicha/mm/2118/acs-2118.js?_=237422两个URL后使用debugger
erine回答传输的URL在https://yiyan.baidu.com/eb/chat/conversation/v2/下
主要bing的验证啥的太麻烦，希望能做一下

**Comment by Redbeanw44602** [comment]
不可能

**Comment by Zack-2023** [comment]
> 不可能

Y

**Comment by Zack-2023** [comment]
> 不可能

可是WAP端用这种方法可以使用debugger抓请求啊

**Comment by Redbeanw44602** [comment]
> > 不可能
> 
> 可是WAP端用这种方法可以使用debugger抓请求啊

不可能的原因不是技术问题

1. 没见过比BingAI能力更强的国内大模型
2. 用国内大模型法律风险太高

综上所述得不偿失，而且我没空，以后可能考虑增加其他国外模型支持，国内压根不在考虑范围内。
