### ISSUE TITLE
BingAI一直提示json异常

### ISSUE THREAD

**Issue by mycbxzd1** [PenUniverse/PenMods-release#204]
### 避免发送重复的问题报告

- [X] 我已检查所有打开的 Issues，确保这个问题没有被提出过

### 异常模块

PenMods (由Mod修改导致的)

### 词典笔型号

YDPG-3

### PenMods 版本

1.3.0预览版

### 词典笔系统版本

1.0.3

### 发生了什么?

BingAI无法使用，提示json错误
![Error](https://github.com/PenUniverse/PenMods-release/assets/140167258/e8bd09d5-7d60-4612-a0d0-fc33bb563d1f)

**Comment by Redbeanw44602** [comment]
1.3.0预览版不支持G3，强制安装不提供任何支持。

**Comment by Zack-2023** [comment]
> ### 避免发送重复的问题报告
> * [x]  我已检查所有打开的 Issues，确保这个问题没有被提出过
> 
> ### 异常模块
> PenMods (由Mod修改导致的)
> 
> ### 词典笔型号
> YDPG-3
> 
> ### PenMods 版本
> 1.3.0预览版
> 
> ### 词典笔系统版本
> 1.0.3
> 
> ### 发生了什么?
> BingAI无法使用，提示json错误 ![Error](https://private-user-images.githubusercontent.com/140167258/311519769-e8bd09d5-7d60-4612-a0d0-fc33bb563d1f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzgzMTYsIm5iZiI6MTcxMDczODAxNiwicGF0aCI6Ii8xNDAxNjcyNTgvMzExNTE5NzY5LWU4YmQwOWQ1LTdkNjAtNDYxMi1hMGQwLWZjMzNiYjU2M2QxZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwNTAwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzJhYTgwMjIxMzVlOTMzYjFmYmU5ZTNkMGIyYjAxY2UwNDQ2OWU4Y2VmZGJlNzhhNDJhNmY0NWVhYThlYmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c72vxgeAhOGv3bIe9u3pRP9QvOCw3cbKGO_QGjw2LEw)
> 
> ### 复现此问题的步骤
> _No response_

一句话：你没用代理，而bing chat在国内无法直接访问
请移步[discussions](https://github.com/PenUniverse/PenMods-release/discussions)了解相关信息
