### ISSUE TITLE
套接字符串发生错误代码0

### ISSUE THREAD

**Issue by mycbxzd1** [PenUniverse/PenMods-release#205]
### 避免发送重复的问题报告

- [X] 我已检查所有打开的 Issues，确保这个问题没有被提出过

### 异常模块

PenMods (由Mod修改导致的)

### 词典笔型号

YDP02x

### PenMods 版本

1.2.0

### 词典笔系统版本

2.0.7

### 发生了什么?

想问一下使用bingAI的时候发生"套接字符串发生错误代码0"是什么情况

**Comment by Redbeanw44602** [comment]
我这里能用，所以不是PenMods的问题。
