### ISSUE TITLE
记录阅读进度遇到长文件时失效

### ISSUE THREAD

**Issue by Spencer-WmlonS** [PenUniverse/PenMods-release#207]
### 避免发送重复的问题报告

- [X] 我已检查所有打开的 Issues，确保这个问题没有被提出过

### 异常模块

PenMods (由Mod修改导致的)

### 词典笔型号

YDP02x

### PenMods 版本

1.3.0

### 词典笔系统版本

2.1.2

### 记录阅读进度功能只对较短文件生效，而较长文件无法记录
测试用文件为 **895KB大小的中文txt** 和 **1KB大小的json文件**
其中只有较小的文件可以被记录阅读位置
- 已尝试手动删除,reading文件无果
-  **无法记录**的具体表现为：大多时候会跳到文章开头，极少情况跳转到文章末尾

**Comment by Redbeanw44602** [comment]
不要发布预览版本的issue，这在“已知问题”中已经告知过了。
