### ISSUE TITLE
成功安装后重启，PenMods不运行，只剩下原版系统

### ISSUE THREAD

**Issue by diyanqi** [PenUniverse/PenMods-release#236]
### 避免发送重复的问题报告

- [X] 我已检查所有打开的 Issues，确保这个问题没有被提出过

### 异常模块

YoudaoDictPen（词典笔主程序自身）

### 词典笔型号

YDP02x

### PenMods 版本

1.3.0 & 1.2.0

### 词典笔系统版本

2.1.2

### 发生了什么?

安装完后重启，在开机页面卡很久，进入系统后penmods已灰飞烟灭、不知所踪。

不知道是词典笔OS更新了反制手段抑或我哪里出了问题。谢谢您🙏

### 复现此问题的步骤

描述一下安装过程：

刚刚安装好PenMods后（这里不论1.2 or 1.3，都试过），是无法触屏的。然后重启，能触屏了，而且penmods正常加载。

到这里一切还正常。

随后，再次重启（用侧边按钮），会在开机页面显示“有道”logo，卡很长时间（比一般开机长），然后会突然黑一下屏然后继续显示开机页面（可能是又重启了？），然后如此往复大概4次。最后终于进入系统，penmods不见了。不过penmods的文件没有删。

现在我的词典笔是 2.1.2 版本，这是升级过的版本，以前低一点可能是 2.1.1 （？），反正那个低一点的版本以前一直用着penmods好好的，突然有一天开机了以后卡了很久，进系统发现penmods寄了。以为是词典笔OS的问题，就升级到了 2.1.2 ，然后再安装penmods，还是同样的，刚安装完还能用，关了一次机就不行了。

另：在第一次出现这种异常状况的前后，我应该没有修改过什么文件。

**Comment by Redbeanw44602** [comment]
系统不干净吧，看你描述的应该是开机时主程序始终拉起失败。这个1.2.0是有可能的，但1.3.0一般来讲不会，建议你重装下系统再装。

**Comment by diyanqi** [comment]
感谢🙏，我发现不装 `youdaoExt` 就没问题了！离谱
