### ISSUE TITLE
通过GPT4Free加入对大部分AI大模型的支持

### ISSUE THREAD

**Issue by imzixel** [PenUniverse/PenMods-release#245]
### 避免发送重复的功能请求

- [X] 我已查看所有打开的 Issues，确保这个功能没有被提出过

### 您遇到了什么问题？

目前Penmod仅支持New Bing，且需要代理才可以正常使用

### 您认为还缺少什么？

可以通过GPT4Free添加对目前大部分AI大模型的支持，且大部分不需要代理就可使用，如GPT-4o、Claude 2
https://github.com/xtekky/gpt4free
需要Python3.10及以上

**Comment by Redbeanw44602** [comment]
1.4.0的更新规划重点在增强AI，但还是主要支持官方的API，这种项目不考虑使用。
