### ISSUE TITLE
志特s6笔

### ISSUE THREAD

**Issue by Funmoring46** [PenUniverse/PenMods-release#251]
### 避免发送重复的功能请求

- [X] 我已查看所有打开的 Issues，确保这个功能没有被提出过

### 您遇到了什么问题？

（请注意:我的中文很不好）

你们可以志特用s6比吗？我好想试试

### 您认为还缺少什么？

缺少了s6笔

**Comment by Redbeanw44602** [comment]
暂时没有计划
