### ISSUE TITLE
移植科大讯飞？

### ISSUE THREAD

**Issue by hseermc** [PenUniverse/PenMods-release#270]
### 避免发送重复的功能请求

- [X] 我已查看所有打开的 Issues，确保这个功能没有被提出过

### 您遇到了什么问题？

科大讯飞的词典笔开放了FTP传入Qt库，penmod也是用Qt写的，请问可以移植吗？

### 您认为还缺少什么？

支持科大讯飞

**Comment by Redbeanw44602** [comment]
暂时没有精力去搞别的品牌的笔
