### ISSUE TITLE
最近入手了一款有道词典笔s6 (ydps6-1),总之我把它拆开了，发现了它里面有一个cv1835芯片，没发现其他像主控的东西，所以我们可以合理推测它就是主控，毕竟它有

### ISSUE THREAD

**Issue by zlbasdfghjkla** [PenUniverse/PenMods-release#272]
最近入手了一款有道词典笔s6 (ydps6-1),总之我把它拆开了，发现了它里面有一个cv1835芯片，没发现其他像主控的东西，所以我们可以合理推测它就是主控，毕竟它有
![image](https://github.com/PenUniverse/PenMods-release/assets/149918799/6eec022e-003d-4c3a-8cbc-649c9ce57071)
所以我去看了文档，发现它有量产工具，但是驱动问题我暂时没有解决。没有思路但想折腾的可以顺着我的思路做

_Originally posted by @3588044667HZ in https://github.com/PenUniverse/PenMods-release/discussions/178_

**Comment by Redbeanw44602** [comment]
再瞎发block了
