### ISSUE TITLE
音乐浮球关闭后音乐可能再次播放

### ISSUE THREAD

**Issue by JetSquid** [PenUniverse/PenMods-release#35]
先随便播放音乐，然后退出到主屏幕，出现音乐浮球，点击音乐浮球关闭音乐后，后台音乐仍然在播放

**Comment by Redbeanw44602** [comment]
无法复现

**Comment by JetSquid** [comment]
从1.0.1或者说1.1.0ota到1.1.6时出现该问题。
&nbsp;


纨绔の少年
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月3日(星期五) 下午5:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PenUniverse/PenMods-release] penmods1.1.6音乐浮球关闭后仍在播放音乐 (Issue #35)





 
无法复现

**Comment by Redbeanw44602** [comment]
刚刚复现了，将在 1.2.0 修复，请留意更新
