### ISSUE TITLE
手动输入查词功能失效

### ISSUE THREAD

**Issue by JetSquid** [PenUniverse/PenMods-release#36]
点击查词功能，手动输入没有弹出来，而是扫描单词教程的界面

**Comment by Redbeanw44602** [comment]
这个功能需要手动开启，所以你开了吗

**Comment by JetSquid** [comment]
我试试


&nbsp;


纨绔の少年
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月3日(星期五) 下午5:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PenUniverse/PenMods-release] penmods1.1.6手动输入查词功能失效 (Issue #36)





 
这个功能需要手动开启，所以你开了吗
