### ISSUE TITLE
增加可选开启或关闭文件管理器的选项

### ISSUE THREAD

**Issue by JetSquid** [PenUniverse/PenMods-release#41]
将文件管理器作为一个可选功能，开启时是文件管理器，关闭时是有道原版的我的导入，因为该功能是一个beta功能，让有需求的人对其进行使用和测试，减少大量重复问题反复提交

建议：在开发者选项中增加该选项，开启和关闭用kidp软重启实现

**Comment by Redbeanw44602** [comment]
MOD文件管理器是原版文件管理器的超级，暂不计划提供关闭选项。
