### ISSUE TITLE
防盗卖措施容易被破解

### ISSUE THREAD

**Issue by luluandpipi** [PenUniverse/PenMods-release#51]
**防盗卖措施（PenMods.md）容易被破解**

现尝试更改其内容，附图如下：

![wayland-screenshot-2023-02-05_18-06-01](https://user-images.githubusercontent.com/110215440/216812999-d88a3cf7-7c2e-408a-8f2a-adcf959aea37.png)

![wayland-screenshot-2023-02-05_18-06-18](https://user-images.githubusercontent.com/110215440/216813011-c01dfd3c-97c5-4a55-94d3-98d8f7980ad9.png)

重启后既不会还原也不会卸载.

此 issue 具有三重含义：）

**Comment by Redbeanw44602** [comment]
你这是啥，也不是`PenMods.md`啊？

**Comment by JetSquid** [comment]
有没有可能，他是把开机创建的penmods.md改成开机创建ydpmod.md，

**Comment by luluandpipi** [comment]
sd
