### ISSUE TITLE
本人的一些建议

### ISSUE THREAD

**Issue by whitersmile** [PenUniverse/PenMods-release#52]
1.查词界面左侧（返回按钮下面）添加收藏，发音按钮
2.扫描后自动添加单词本功能加一个屏蔽句子功能的开关，因为扫词的时候经常漏扫多扫，但也会添加到单词本中
3.控制中心右边两个按钮功能自定义，比如开手电筒，切换握笔方向，关闭扫词功能（有时候躲被子里听歌会不小心触发扫词功能把歌停掉）
4.音量条和亮度条调节个人觉得 按滑动距离增减音量 比直接按照手指位置增减 的逻辑更好
5.网易系统自带的返回键切歌bug（单词本点及查看退出后会切歌），以及不会保存播放位置的播放器
最后感谢作者的插件，优化后的系统比原来网易的垃圾系统好太多了！简直是梦中情笔，摸鱼神器。让我小小期待一下后续的MP4功能吧

**Comment by JetSquid** [comment]
5.的bug我已经提过了，建议你先看一遍issues有没有和你一样的，不要提重复问题，减少群主的工作量。1.词典笔查词本来就有这个按钮啊，个人认为没有必要多加，毕竟屏幕就怎么大，4.不是本来就按滑动距离增减音量吗？

**Comment by whitersmile** [comment]
> 5.的bug我已经提过了，建议你先看一遍issues有没有和你一样的，不要提重复问题，减少群主的工作量。1.词典笔查词本来就有这个按钮啊，个人认为没有必要多加，毕竟屏幕就怎么大，4.不是本来就按滑动距离增减音量吗？

忘说了，本人的词典笔2.0经典版
1.这个主要是因为扫词收藏还要往下滑，但是2.0的触屏不灵敏，采样率也低，经常导致滑动误触，左边的区域空着正好可以加这个功能，方便很多。
4.如果你用的是miui的话可以试试系统音量条的滑动调节和现在2.0系统的调节方式有什么不同，词穷了感觉表达不准确。

**Comment by Redbeanw44602** [comment]
请拆分此issue。
