### ISSUE TITLE
防盗卖措施容易被破解，以及其实现方法

### ISSUE THREAD

**Issue by luluandpipi** [PenUniverse/PenMods-release#58]
**防盗卖措施（自动创建PenMods.md）容易被破解**

我尝试篡改了 PenMods，使其开机时**创建 `YDPMods.md` 文件而不是 `PenMods.md` 文件，**
并且修改了文件的内容，包括名称、项目官网、QQ群等内容（如图）：

![wayland-screenshot-2023-02-05_18-06-01](https://user-images.githubusercontent.com/110215440/216812999-d88a3cf7-7c2e-408a-8f2a-adcf959aea37.png)

![wayland-screenshot-2023-02-05_18-06-18](https://user-images.githubusercontent.com/110215440/216813011-c01dfd3c-97c5-4a55-94d3-98d8f7980ad9.png)

一种 “破解” PenMods 防盗卖措施的实现

**Comment by Redbeanw44602** [comment]
没有绝对的安全系统，`1.1.7` 中为修改增加了一些难度。

**Comment by luluandpipi** [comment]
> 没有绝对的安全系统，`1.1.7` 中为修改增加了一些难度。再说那种盗卖垃圾人也不见得有能力改这东西。

那也是

**Comment by luluandpipi** [comment]
已修改 PenMods 1.1.8，仅做安全测试，不是要求增强
**现在已经足够安全了，没必要再改了
这下倒卖的绝对改不了了：）**
