### ISSUE TITLE
反馈：安全设置项未保存密码可以退出

### ISSUE THREAD

**Issue by JetSquid** [PenUniverse/PenMods-release#6]
在安全设置项中如果初次使用没有密码，启用密码后强烈建议直接跳转到设置密码，而不是在安全选项的页面，而且要加一个设置密码后才可以退出的功能，防止未设置密码但是却退出安全设置项导致不能再次进入安全设置项，需要手动重新刷入penmods或者重刷system分区

**Comment by Redbeanw44602** [comment]
默认密码 `abcd`，介绍中有说的。
