### ISSUE TITLE
建议修改控制中心

### ISSUE THREAD

**Issue by libiao2333** [PenUniverse/PenMods-release#78]
控制中心两个调节太大了（个人觉得），建议把调节换成和设置一样的圆点拖动，然后在空余出来的地方加上时间和电量

**Comment by JetSquid** [comment]
我个人比较喜欢现在的，时间和音量主屏幕已经有的，屏幕本身就小，没必要再加，而且可能其他人也不喜欢

**Comment by libiao2333** [comment]
> 我个人比较喜欢现在的，时间和音量主屏幕已经有的，屏幕本身就小，没必要再加，而且可能其他人也不喜欢

主要是他文档不是一页一页的，每次看电量看时间还得退出去，然后下一次就找不到阅读进度了🤦‍

**Comment by JetSquid** [comment]
有没有可能，这个可以归纳到给txt增加书签功能

**Comment by Redbeanw44602** [comment]
控制中心以后会有优化
