### ISSUE TITLE
建议把文档改成翻页式

### ISSUE THREAD

**Issue by libiao2333** [PenUniverse/PenMods-release#82]
下滑式不好找进度，这样做什么都不太好回去，例如我想去看个电量，我回来还得滑滑滑，你刚开始看还算友好，你看到不上不下不前不后的地方真的很难找到，建议大大把文档改成翻页的，然后退出之后自动保存当前页，下次看就能接着继续了

**Comment by Redbeanw44602** [comment]
发issue前先去看是不是别人发过的谢谢
