### ISSUE TITLE
1.8.0无法更新

### ISSUE THREAD

**Issue by libiao2333** [PenUniverse/PenMods-release#87]
可能是我问题，但是我已经重启+断网过了，还是不行，下载完成后点击安装提示校验失败

**Comment by libiao2333** [comment]
打错了，是1.1.8，sorry🤦‍

**Comment by libiao2333** [comment]
提一嘴，空间充足，还有6GB

**Comment by JetSquid** [comment]
你没有进群吗？

**Comment by libiao2333** [comment]
> 你没有进群吗？

昨天家长查QQ退了，真无语了，都初中了还管

**Comment by libiao2333** [comment]
已重装penmod，还是校验失败

**Comment by libiao2333** [comment]
libPenmod.so是撒QAQ

**Comment by libiao2333** [comment]
好吧，我放弃研究了，能不能手动更新啊QAQ

**Comment by libiao2333** [comment]
我用adb把libPenMods.so替换了，但还是校验失败

**Comment by ljlVink** [comment]
```
adb push .\libPenMods.so /userdisk/Loader

adb reboot
```

**Comment by JetSquid** [comment]
。。。

**Comment by JetSquid** [comment]
![wayland-screenshot-2023-03-06_12-58-06](https://user-images.githubusercontent.com/123063894/223036846-a57e1268-83db-44e3-a801-bca9845f6ab7.png)

**Comment by JetSquid** [comment]
不能通过ota升级

**Comment by libiao2333** [comment]
> 不能通过ota升级

对啊，所以我昨天尝试替换了libPenMods.so啊

**Comment by libiao2333** [comment]
怎..怎么办...我替换了libPenMods.so后这玩意把penmod刷掉了，用penmod安装系统提示已经安装了

**Comment by libiao2333** [comment]
OK啊，重装了penmod，坐等大佬救我

**Comment by libiao2333** [comment]
！！！！！终于！更新完了！

提一嘴，push的路径（不是userdisk的路径噢！）要加双引号

**Comment by JetSquid** [comment]
这里不是聊天区域，而是用来提issue的区域，你应该简洁明了的说明问题，而不是说一堆废话，penmods更新在群里已经讨论过了，这里主要提的是penmods相关功能的问题，你在这里提的问题很可能得不到解答，不按标准提问格式进行提问，你的提问权限可能会被剥夺，或者不会被他人所理会，你应该进群交流这类问题。

**Comment by JetSquid** [comment]
> ！！！！！终于！更新完了！
> 
> 提一嘴，push的路径（不是userdisk的路径噢！）要加双引号

如果你已经自行解决，请关闭此issue

**Comment by libiao2333** [comment]
...笑，我发了3遍进群，没同意，你猜我为什么在这提？



在 2023-03-08 12:13:53，"JetSquid" ***@***.***> 写道：

这里不是聊天区域，而是用来提issue的区域，你应该简洁明了的说明问题，而不是说一堆废话，penmods更新在群里已经讨论过了，这里主要提的是penmods相关功能的问题，你在这里提的问题很可能得不到解答，不按标准提问格式进行提问，你的提问权限可能会被剥夺，或者不会被他人所理会，你应该进群交流这类问题。

**Comment by JetSquid** [comment]
你要自己反思一下自己为什么进不去，issue是让你这样提的？我才笑，建议你不要用penmods了，下次来这里提也没人理你，信不信？

**Comment by Redbeanw44602** [comment]
已将此Issue会话的主要参与者Block，请各位自行反思为什么采取该惩罚。
