### ISSUE TITLE
输入法扫描输入故障

### ISSUE THREAD

**Issue by JetSquid** [PenUniverse/PenMods-release#88]
![wayland-screenshot-2023-03-06_12-55-19](https://user-images.githubusercontent.com/123063894/223037080-0cc6855c-f5fa-4b24-a6dd-893d5d2b727f.png)
![wayland-screenshot-2023-03-06_14-37-11](https://user-images.githubusercontent.com/123063894/223037086-2dde2754-febd-4285-9762-f1141d392822.png)
在文件管理中使用输入法更改文件名字时出现bug

**Comment by Redbeanw44602** [comment]
#96
