### ISSUE TITLE
wifi界面被隐藏

### ISSUE THREAD

**Issue by xCipHanD** [PenUniverse/PenMods-release#93]
### 异常模块

PenMods (由Mod修改导致的)

### 词典笔型号

YDP02x

### PenMods 版本

1.1.8

### 词典笔系统版本

2.0.7

### 发生了什么?

wifi设置界面部分被隐藏

### 复现此问题的步骤

复现:
1.点开“查词翻译”
2.使用翻译笔扫描任意文字（物理）
3.使用下滑菜单，长按wifi图标，发现部分界面被隐藏

**Comment by Redbeanw44602** [comment]
可能与 #88 有关
