### ISSUE TITLE
PenMods的禁用自动发言 和 原版系统的自动发音 设置项冲突

### ISSUE THREAD

**Issue by Gouzuang** [PenUniverse/PenMods-release#94]
### 异常模块

PenMods (由Mod修改导致的)

### 词典笔型号

YDP02x

### PenMods 版本

1.1.8

### 词典笔系统版本

2.0.7

### 发生了什么?

PenMods在 安全>社会安全选项 中提供了 禁用自动发言 的设置项，但原版系统本身已经有 自动发音>扫描后自动发音 的设置。
且如果没有开启 PenMods提供的 禁用自动发言 选项，那系统原本的设置会在设备重启后重新开启。
另外， PenMods在 音量 中提供了 发音语速 的设置，是否可以整合到 自动发音 设置项中？

**Comment by Redbeanw44602** [comment]
问题讲不清楚吗？另外PenMod没有提供发音语速设置。
