### ISSUE TITLE
当前文本浏览较为羸弱，可以添加下列功能

### ISSUE THREAD

**Issue by Alicedrop** [PenUniverse/PenMods-release#99]
### 您遇到了什么问题？

现在文本浏览看起来既不像阅读器又不能用来进行一些常用的操作。

### 您认为还缺少什么？

希望可以给文本浏览添加可拖动进度条、编辑、甚至是查找替换来提升实用性。实际上甚至可以看看那个语音识别是怎么调用的，可以尝试用那个搞个语音输入。

**Comment by Redbeanw44602** [comment]
#63
